Repository rwth-acis/VIAProMa, pull requests merged in 2022-01, with the labels that each got.

#316 DeepLink | Combined functions, added documentation, general cleanup
  Frontend/VIAProMa/Assets/MRTK/Core/Utilities.meta
  Frontend/VIAProMa/Assets/Scenes/MainScene.unity
  Frontend/VIAProMa/Assets/Scripts/DeepLinks/DeepLinkBootstrapper.cs
  Frontend/VIAProMa/Assets/Scripts/DeepLinks/DeepLinkManager.cs
  Frontend/VIAProMa/Assets/Scripts/DeepLinks/InviteLinks/InviteLinkGenerator.cs
  Frontend/VIAProMa/Assets/Scripts/DeepLinks/InviteLinksHandler.cs
  Frontend/VIAProMa/Assets/Scripts/DeepLinks/VIAProMaDeepLinks.md
Labels: documentation

#326 DeepLinks | Added UI for Invite Link Generation
  Frontend/VIAProMa/Assets/Prefabs/Managers.prefab
  Frontend/VIAProMa/Assets/Prefabs/Multiplayer/Resources/Avatar Networked.prefab
  Frontend/VIAProMa/Assets/Prefabs/UI/Main Menu.prefab
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/Connection Window.prefab
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/InviteLink Window.prefab
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/InviteLink Window.prefab.meta
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/LoginMenu.prefab
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/Rooms Window.prefab
  Frontend/VIAProMa/Assets/Scenes/MainScene.unity
  Frontend/VIAProMa/Assets/Scripts/DeepLinks/InviteLinks/InviteLinkManager.cs
  Frontend/VIAProMa/Assets/Scripts/DeepLinks/InviteLinks/InviteLinkMenu.cs
  Frontend/VIAProMa/Assets/Scripts/DeepLinks/InviteLinks/InviteLinkMenu.cs.meta
  Frontend/VIAProMa/Assets/Scripts/DeepLinks/InviteLinks/InviteLinksHandler.cs
  Frontend/VIAProMa/Assets/Scripts/DeepLinks/InviteLinks/InviteLinksHandler.cs.meta
  Frontend/VIAProMa/Assets/Scripts/UI/Main Menu Cube/MainMenu.cs
  Frontend/VIAProMa/Assets/Scripts/UI/WindowManager.cs
  Frontend/VIAProMa/ProjectSettings/QualitySettings.asset
Labels: enhancement

#331 fixed the SectionPlacer Script by changing scope of a variable
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/SectionBoard/TextPlacer.cs
Labels: enhancement

#325 Close #295 Improved KeyboardTourTask and added some basic documentation
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/InteractableTaskEventHandler.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/InteractableTaskEventHandler.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/InteractableTourTask.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/InteractableTourTask.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/KeyboardTaskEventHandler.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/KeyboardTourTask.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/KeyboardTourTask.cs.meta
Labels: enhancement, documentation

#344 GuidedTour | Prototype finished
  Frontend/VIAProMa/Assets/GuidedTour/Configuration/GuidedTour.json
  Frontend/VIAProMa/Assets/GuidedTour/Scenes/GuidedTourScene.unity
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourManager.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/SectionBoard/TextPlacer.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/KeyboardTaskEventHandler.cs.meta
  Frontend/VIAProMa/Assets/Prefabs/Shelves/Resources/GuidedTour_IssueShelf.prefab
  Frontend/VIAProMa/Assets/Prefabs/Shelves/Resources/GuidedTour_IssueShelf.prefab.meta
Labels: enhancement

#345 GuidedTour | Merge Develop in Master
  Frontend/VIAProMa/Assets/GuidedTour.meta
  Frontend/VIAProMa/Assets/GuidedTour/Configuration.meta
  Frontend/VIAProMa/Assets/GuidedTour/Configuration/GuidedTour.json
  Frontend/VIAProMa/Assets/GuidedTour/Configuration/GuidedTour.json.meta
  Frontend/VIAProMa/Assets/GuidedTour/Prefabs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Prefabs/GuidedTourWidget.prefab
  Frontend/VIAProMa/Assets/GuidedTour/Prefabs/GuidedTourWidget.prefab.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scenes.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scenes/GuidedTourScene.unity
  Frontend/VIAProMa/Assets/GuidedTour/Scenes/GuidedTourScene.unity.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scenes/SectionBoardTest.unity
  Frontend/VIAProMa/Assets/GuidedTour/Scenes/SectionBoardTest.unity.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/Configuration.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/Configuration/ConfigFile.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/Configuration/ConfigFile.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/Configuration/ConfigFileTypes.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/Configuration/ConfigFileTypes.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourManager.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourManager.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourUtils.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourUtils.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourWidget.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourWidget.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/SectionBoard.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/SectionBoard/TextPlacer.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/SectionBoard/TextPlacer.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/AbstractTourTask.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/AbstractTourTask.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/InteractableTaskEventHandler.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/InteractableTaskEventHandler.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/InteractableTourTask.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/InteractableTourTask.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/KeyboardTourTask.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/KeyboardTourTask.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/SimpleTourTask.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/SimpleTourTask.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/TourSection.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/TourSection.cs.meta
  Frontend/VIAProMa/Assets/Materials/Button.mat
  Frontend/VIAProMa/Assets/Prefabs/Multiplayer/Resources/Avatar Networked.prefab
  Frontend/VIAProMa/Assets/Prefabs/Shelves/Resources/GuidedTour_IssueShelf.prefab
  Frontend/VIAProMa/Assets/Prefabs/Shelves/Resources/GuidedTour_IssueShelf.prefab.meta
  Frontend/VIAProMa/Assets/Prefabs/Shelves/Resources/VisualizationShelf.prefab
  Frontend/VIAProMa/Assets/Prefabs/Visualizations/Resources/CommitStatisticsVisualization.prefab
  Frontend/VIAProMa/Assets/Prefabs/Visualizations/Resources/Kanban Board Column.prefab
Labels: enhancement

#362 GuidedTour | Changes in logic of the GuidedTourManager
  Frontend/VIAProMa/Assets/GuidedTour/Configuration/GuidedTour.json
  Frontend/VIAProMa/Assets/GuidedTour/Scenes/GuidedTourScene.unity
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourManager.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourUtils.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/AbstractTourTask.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/InteractableTaskEventHandler.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/InteractableTourTask.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/KeyboardTourTask.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/SimpleTourTask.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/UnlinkedTourTask.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/UnlinkedTourTask.cs.meta
  Frontend/VIAProMa/Assets/Prefabs/Shelves/Resources/GuidedTour_IssueShelf.prefab
Labels: enhancement

#366 GuidedTour | Implemented multi language support
  Frontend/VIAProMa/Assets/GuidedTour/Configuration/GuidedTour.json
  Frontend/VIAProMa/Assets/GuidedTour/Configuration/Languages.json
  Frontend/VIAProMa/Assets/GuidedTour/Configuration/Languages.json.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scenes/GuidedTourScene.unity
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/Configuration/LanguageFile.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/Configuration/LanguageFile.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/Configuration/LanguageFileTypes.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/Configuration/LanguageFileTypes.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourManager.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourUtils.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourWidget.cs
Labels: enhancement

#370 Guided tour/indicator
  Frontend/VIAProMa/Assets/GuidedTour/Materials.meta
  Frontend/VIAProMa/Assets/GuidedTour/Materials/No Name 1.mat
  Frontend/VIAProMa/Assets/GuidedTour/Materials/No Name 1.mat.meta
  Frontend/VIAProMa/Assets/GuidedTour/Materials/No Name.mat
  Frontend/VIAProMa/Assets/GuidedTour/Materials/No Name.mat.meta
  Frontend/VIAProMa/Assets/GuidedTour/Models.meta
  Frontend/VIAProMa/Assets/GuidedTour/Models/GT_Highlighter.fbx
  Frontend/VIAProMa/Assets/GuidedTour/Models/GT_Highlighter.fbx.meta
  Frontend/VIAProMa/Assets/GuidedTour/Models/GT_IndicatorArrow.fbx
  Frontend/VIAProMa/Assets/GuidedTour/Models/GT_IndicatorArrow.fbx.meta
  Frontend/VIAProMa/Assets/GuidedTour/Prefabs/GT_HighlighterPrefab.prefab
  Frontend/VIAProMa/Assets/GuidedTour/Prefabs/GT_HighlighterPrefab.prefab.meta
  Frontend/VIAProMa/Assets/GuidedTour/Prefabs/IndicatorArrowsPrefab.prefab
  Frontend/VIAProMa/Assets/GuidedTour/Prefabs/IndicatorArrowsPrefab.prefab.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scenes/GuidedTourScene.unity
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourManager.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/HighlighterAnimation.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/HighlighterAnimation.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/AbstractTourTask.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/InteractableTourTask.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/InteractableTourTask.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/KeyboardTourTask.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/SimpleTourTask.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/TourTasks/UnlinkedTourTask.cs
  Frontend/VIAProMa/Assets/MixedRealityToolkit.Generated/ProjectPreferences.asset
  Frontend/VIAProMa/Assets/Prefabs/Multiplayer/Resources/Avatar Networked.prefab
Labels: enhancement

#372 Created Notification Box #352
  Frontend/VIAProMa/Assets/GuidedTour/Prefabs/Notification Widget Guided Tour.prefab
  Frontend/VIAProMa/Assets/GuidedTour/Prefabs/Notification Widget Guided Tour.prefab.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/NotoficationWidget.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/NotoficationWidget.cs.meta
Labels: enhancement

#373 Changed SectionBoard to be more lightweight and fit in with VIAProMas…
  Frontend/VIAProMa/Assets/GuidedTour/Prefabs/SectionBoardPrefab.prefab
  Frontend/VIAProMa/Assets/GuidedTour/Prefabs/SectionBoardPrefab.prefab.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scenes/SectionBoardTest.unity
  Frontend/VIAProMa/Assets/GuidedTour/Scenes/redesign.unity
  Frontend/VIAProMa/Assets/GuidedTour/Scenes/redesign.unity.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/GuidedTourManager.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/SectionBoard.cs
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/SectionBoard.cs.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scripts/SectionBoard/TextPlacer.cs
Labels: enhancement

#382 Guided tour/tour content
  Frontend/VIAProMa/Assets/GuidedTour/Configuration/GuidedTour.json
  Frontend/VIAProMa/Assets/GuidedTour/Configuration/Languages.json
  Frontend/VIAProMa/Assets/GuidedTour/Prefabs/GT_AvatarConfigurator.prefab
  Frontend/VIAProMa/Assets/GuidedTour/Prefabs/GT_AvatarConfigurator.prefab.meta
  Frontend/VIAProMa/Assets/GuidedTour/Prefabs/GT_ConnectionWindow.prefab
  Frontend/VIAProMa/Assets/GuidedTour/Prefabs/GT_ConnectionWindow.prefab.meta
  Frontend/VIAProMa/Assets/GuidedTour/Prefabs/GT_RoomsWindow.prefab
  Frontend/VIAProMa/Assets/GuidedTour/Prefabs/GT_RoomsWindow.prefab.meta
  Frontend/VIAProMa/Assets/GuidedTour/Scenes/GuidedTourScene.unity
  Frontend/VIAProMa/Assets/Prefabs/Shelves/Resources/GuidedTour_IssueShelf.prefab
Labels: enhancement

#390 DeepLink | (hopefully) final fixes
  Frontend/VIAProMa/Assets/Scripts/DeepLinks/DeepLinkBootstrapper.cs
  Frontend/VIAProMa/Assets/Scripts/DeepLinks/InviteLinks/ConfirmationWindow.cs
  Frontend/VIAProMa/Assets/Scripts/DeepLinks/InviteLinks/InviteLinkMenu.cs
Labels: bug

#392 coroutine while PhotonNetwork not in Lobby
  Frontend/VIAProMa/Assets/Scripts/DeepLinks/DeepLinkBootstrapper.cs
Labels: bug
