Repository rwth-acis/VIAProMa, pull requests merged in 2022-07, with the labels that each got.

#474 Drag and Drop Implemented Overlap Indicator feature
  Frontend/VIAProMa/Assets/Tests/DragAndDrop/Card With DandD.prefab
  Frontend/VIAProMa/Assets/Tests/DragAndDrop/DragAndDrop.cs
Labels: enhancement, 2 - Priority Medium

#476 Drag and Drop Speed condition functionality fully implemented
  Frontend/VIAProMa/Assets/Tests/DragAndDrop/DragAndDrop.cs
Labels: enhancement

#475 Drag and Drop delete issues after adding them
  Frontend/VIAProMa/Assets/Scripts/UI/AppBar/AppBarActions.cs
  Frontend/VIAProMa/Assets/Tests/DragAndDrop/DragAndDrop.cs
Labels: enhancement, 2 - Priority Medium

#483 Added Documentation to Task Card List Implementation
  Frontend/VIAProMa/Assets/Prefabs/UI/Configuration Windows/Issue List/Issue List Window.prefab
  Frontend/VIAProMa/Assets/Prefabs/UI/Configuration Windows/Progress Bar Configuration Window.prefab
  Frontend/VIAProMa/Assets/Scripts/Visualizations/Configuration Window Core/ConfigurationIssueListUI.cs
Labels: documentation

#482 Drag and drop integrated features into project and cleanup
  Frontend/VIAProMa/Assets/Prefabs/Resources/Card In Scene.prefab
  Frontend/VIAProMa/Assets/Prefabs/Visualizations/BuildingProgress Bar/Apartment Building 1.prefab
  Frontend/VIAProMa/Assets/Prefabs/Visualizations/BuildingProgress Bar/Appartment Building 2.prefab
  Frontend/VIAProMa/Assets/Prefabs/Visualizations/BuildingProgress Bar/EiffelTower.prefab
  Frontend/VIAProMa/Assets/Prefabs/Visualizations/BuildingProgress Bar/JapaneseTemple.prefab
  Frontend/VIAProMa/Assets/Prefabs/Visualizations/BuildingProgress Bar/LeaningTower.prefab
  Frontend/VIAProMa/Assets/Prefabs/Visualizations/BuildingProgress Bar/Paris Church.prefab
  Frontend/VIAProMa/Assets/Prefabs/Visualizations/BuildingProgress Bar/Skyscraper1.prefab
  Frontend/VIAProMa/Assets/Prefabs/Visualizations/BuildingProgress Bar/Skyscraper2.prefab
  Frontend/VIAProMa/Assets/Prefabs/Visualizations/Competence Display/Resources/CompetenceDisplay.prefab
  Frontend/VIAProMa/Assets/Scripts/DragAndDrop.cs
  Frontend/VIAProMa/Assets/Scripts/DragAndDrop.cs.meta
  Frontend/VIAProMa/Assets/Tests/DragAndDrop/Card With DandD.prefab
  Frontend/VIAProMa/Assets/Tests/DragAndDrop/Card With DandD.prefab.meta
  Frontend/VIAProMa/Assets/Tests/DragAndDrop/DragAndDropTest.unity
  Frontend/VIAProMa/Assets/Tests/DragAndDrop/DragAndDropTestRunner.cs
  Frontend/VIAProMa/Assets/Tests/DragAndDrop/DragAndDropTestSettings.lighting
  Frontend/VIAProMa/Assets/Tests/DragAndDrop/DragAndDropTestSettings.lighting.meta
  Frontend/VIAProMa/UserSettings/EditorUserSettings.asset
Labels: 1 - Priority High

#481 New Feature: Anchoring System
  Frontend/VIAProMa/Assets/3D Models/Anchor.fbx
  Frontend/VIAProMa/Assets/3D Models/Anchor.fbx.meta
  Frontend/VIAProMa/Assets/AnchorManager.cs
  Frontend/VIAProMa/Assets/AnchorManager.cs.meta
  Frontend/VIAProMa/Assets/AnchoringMenu.cs
  Frontend/VIAProMa/Assets/AnchoringMenu.cs.meta
  Frontend/VIAProMa/Assets/DebugText.cs
  Frontend/VIAProMa/Assets/DebugText.cs.meta
  Frontend/VIAProMa/Assets/MixedRealityToolkit.Generated/ProjectPreferences.asset
  Frontend/VIAProMa/Assets/Prefabs/Managers.prefab
  Frontend/VIAProMa/Assets/Prefabs/Multiplayer/Resources/Avatar Networked.prefab
  Frontend/VIAProMa/Assets/Prefabs/Resources/Card In Scene.prefab
  Frontend/VIAProMa/Assets/Prefabs/Shelves/Resources/VisualizationShelf.prefab
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/AnchoringMenu.prefab
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/AnchoringMenu.prefab.meta
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/LoginMenu.prefab
  Frontend/VIAProMa/Assets/Prefabs/Visualizations/Resources/CommitStatisticsVisualization.prefab
  Frontend/VIAProMa/Assets/Prefabs/Visualizations/Resources/Kanban Board Column.prefab
  Frontend/VIAProMa/Assets/Scenes/MainScene.unity
  Frontend/VIAProMa/Assets/Scripts/ResourceManager/ResourceManager.cs
  Frontend/VIAProMa/Assets/Scripts/SaveLoadSystem/Core/SaveLoadManager.cs
  Frontend/VIAProMa/Assets/Scripts/ScriptableObjects/Multiplayer/Resources/NetworkPrefabs.asset
  Frontend/VIAProMa/Assets/Scripts/Shelf/Widgets/CopyMover.cs
  Frontend/VIAProMa/Assets/Scripts/UI/Main Menu Cube/MainMenu.cs
  Frontend/VIAProMa/Assets/Scripts/UI/WindowManager.cs
  Frontend/VIAProMa/Assets/Textures/Icons/Anchor.png
  Frontend/VIAProMa/Assets/Textures/Icons/Anchor.png.meta
  Frontend/VIAProMa/Assets/Textures/Icons/Unlock.png
  Frontend/VIAProMa/Assets/Textures/Icons/Unlock.png.meta
  Frontend/VIAProMa/Packages/manifest.json
  Frontend/VIAProMa/Packages/packages-lock.json
  Frontend/VIAProMa/ProjectSettings/TagManager.asset
Labels: enhancement
