Repository rwth-acis/VIAProMa, pull requests merged in 2023-01, with the labels that each got.

#533 Analytics Frontend changes
  Frontend/VIAProMa/.gitignore
  Frontend/VIAProMa/Assets/Scenes/MainScene.unity
  Frontend/VIAProMa/Assets/Scripts/Analytics.meta
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsManager.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsManager.cs.meta
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsSettings.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsSettings.cs.meta
  Frontend/VIAProMa/Assets/Scripts/Analytics/LogTypes.meta
  Frontend/VIAProMa/Assets/Scripts/Analytics/LogTypes/Logpoint.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/LogTypes/Logpoint.cs.meta
  Frontend/VIAProMa/Assets/Scripts/Analytics/LogTypes/LogpointIssueSelected.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/LogTypes/LogpointIssueSelected.cs.meta
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observer.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observer.cs.meta
  Frontend/VIAProMa/Assets/Scripts/Analytics/wiki.md
  Frontend/VIAProMa/Assets/Scripts/Analytics/wiki.md.meta
  Frontend/VIAProMa/Assets/Scripts/Shelf/Widgets/CopyMover.cs
Labels: Team PMSL, mixed-reality-lab

#535 Adding analytics toggle button
  Backend/gradle.properties
  Frontend/VIAProMa/Assets/MixedRealityToolkit.Generated/ProjectPreferences.asset
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/Advanced Settings.prefab
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/Advanced Settings.prefab.meta
  Frontend/VIAProMa/Assets/Scenes/MainScene.unity
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsManager.cs
  Frontend/VIAProMa/Assets/Scripts/UI/AdvancedSettingsMenu.cs
  Frontend/VIAProMa/Assets/Scripts/UI/AdvancedSettingsMenu.cs.meta
  Frontend/VIAProMa/Assets/Scripts/UI/Main Menu Cube/MainMenu.cs
  Frontend/VIAProMa/Assets/Scripts/UI/WindowManager.cs
Labels: Team PMSL, mixed-reality-lab

#536 Added new logging type for gaze detection
  Frontend/VIAProMa/Assets/Scripts/Analytics/LogTypes/LogpointGazedAt.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/LogTypes/LogpointGazedAt.cs.meta
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observer.cs
Labels: enhancement, Team PMSL

#543 Pmsl/notification
  Frontend/VIAProMa/Assets/MixedRealityToolkit.Generated/CustomProfiles/New MixedRealityInputSimulationProfile.asset
  Frontend/VIAProMa/Assets/MixedRealityToolkit.Generated/CustomProfiles/New MixedRealityInputSimulationProfile.asset.meta
  Frontend/VIAProMa/Assets/MixedRealityToolkit.Generated/CustomProfiles/New MixedRealityInputSystemProfile.asset
  Frontend/VIAProMa/Assets/MixedRealityToolkit.Generated/CustomProfiles/New MixedRealityInputSystemProfile.asset.meta
  Frontend/VIAProMa/Assets/MixedRealityToolkit.Generated/CustomProfiles/New MixedRealityPointerProfile.asset
  Frontend/VIAProMa/Assets/MixedRealityToolkit.Generated/CustomProfiles/New MixedRealityPointerProfile.asset.meta
  Frontend/VIAProMa/Assets/MixedRealityToolkit.Generated/CustomProfiles/VIAProMaProfile.asset
  Frontend/VIAProMa/Assets/Prefabs/Issue Cards/EmptyCard List View Item.prefab
  Frontend/VIAProMa/Assets/Prefabs/Multiplayer/Resources/Avatar Networked.prefab
  Frontend/VIAProMa/Assets/Prefabs/Resources/Card In Scene.prefab
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/Advanced Settings.prefab
  Frontend/VIAProMa/Assets/Scenes/MainScene.unity
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsManager.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/GazableComponents.meta
  Frontend/VIAProMa/Assets/Scripts/Analytics/GazableComponents/GazableIssueCard.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/GazableComponents/GazableIssueCard.cs.meta
  Frontend/VIAProMa/Assets/Scripts/UI/AdvancedSettings.meta
  Frontend/VIAProMa/Assets/Scripts/UI/AdvancedSettings/AdvancedSettingsMenu.cs
  Frontend/VIAProMa/Assets/Scripts/UI/AdvancedSettings/AdvancedSettingsMenu.cs.meta
Labels: enhancement, Team PMSL, mixed-reality-lab

#545 Implemented gaze detection for analytics
  Frontend/VIAProMa/Assets/Prefabs/Resources/Card In Scene.prefab
  Frontend/VIAProMa/Assets/Scenes/MainScene.unity
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsManager.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/GazableComponents/GazableIssueCard.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/LogTypes/Logpoint.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/LogTypes/LogpointGazedAt.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/LogTypes/LogpointIssueSelected.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observer.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/wiki.md
  Frontend/VIAProMa/Assets/Scripts/SaveLoadSystem/Core/SaveData.cs
  Frontend/VIAProMa/Assets/Scripts/SaveLoadSystem/Core/SaveLoadManager.cs
Labels: enhancement, Team PMSL, mixed-reality-lab

#546 Created menu
  Frontend/VIAProMa/Assets/Prefabs/UI/Main Menu.prefab
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/UndoRedoMenu.prefab
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/UndoRedoMenu.prefab.meta
  Frontend/VIAProMa/Assets/Scenes/MainScene.unity
  Frontend/VIAProMa/Assets/Scripts/UI/Main Menu Cube/MainMenu.cs
  Frontend/VIAProMa/Assets/Scripts/UI/UndoRedoMenu.meta
  Frontend/VIAProMa/Assets/Scripts/UI/UndoRedoMenu/UndoRedoMenu.cs
  Frontend/VIAProMa/Assets/Scripts/UI/UndoRedoMenu/UndoRedoMenu.cs.meta
  Frontend/VIAProMa/Assets/Scripts/UI/WindowManager.cs
Labels: enhancement

#547 Created Command Pattern and integrated Menus + Kanban Board
  Frontend/VIAProMa/Assets/MixedRealityToolkit.Generated/ProjectPreferences.asset
  Frontend/VIAProMa/Assets/Prefabs/Multiplayer/Resources/Avatar Networked.prefab
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/UndoRedoMenu.prefab
  Frontend/VIAProMa/Assets/Prefabs/Visualizations/Resources/Progress Bar.prefab
  Frontend/VIAProMa/Assets/Scenes/MainScene.unity
  Frontend/VIAProMa/Assets/Scripts/UI/Main Menu Cube/MainMenu.cs
  Frontend/VIAProMa/Assets/Scripts/UI/UndoRedoMenu/UndoRedoMenu.cs
  Frontend/VIAProMa/Assets/Scripts/UI/WindowManager.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem.meta
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/CommandController.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/CommandController.cs.meta
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/CommandProcessor.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/CommandProcessor.cs.meta
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/CreateMenuCommand.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/CreateMenuCommand.cs.meta
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/ICommand.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/ICommand.cs.meta
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/MoveCommand.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/MoveCommand.cs.meta
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/ProgressBarHandleCommand.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/ProgressBarHandleCommand.cs.meta
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/ScaleKanbanBoardCommand.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/ScaleKanbanBoardCommand.cs.meta
  Frontend/VIAProMa/Assets/Scripts/Visualizations/Kanban Board/KanbanBoardColumnHandle.cs
  Frontend/VIAProMa/Assets/Scripts/Visualizations/Progress Bar/ProgressBarHandle.cs
  Frontend/VIAProMa/Assets/Tests/UI Tests/Undo-Redo-Menu.meta
  Frontend/VIAProMa/Assets/Tests/UI Tests/VisualizationShelf/VisualizationShelfTestSettings.lighting
  Frontend/VIAProMa/Assets/Tests/UI Tests/VisualizationShelf/VisualizationShelfTestSettings.lighting.meta
  Frontend/VIAProMa/ProjectSettings/ProjectVersion.txt
Labels: enhancement

#553 Removal of Redo() and menu adjustments
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/UndoRedoMenu.prefab
  Frontend/VIAProMa/Assets/Scripts/UI/Main Menu Cube/MainMenu.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/AppBarTransformCommand.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/CommandProcessor.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/CreateMenuCommand.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/ICommand.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/ProgressBarHandleCommand.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/ScaleKanbanBoardCommand.cs
Labels: enhancement

#554 HOTFIX: Added missing namespaces.
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsManager.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsSettings.cs
Labels: bug, Team PMSL, mixed-reality-lab

#556 HOTFIX: Added missing namespace statements
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsManager.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsSettings.cs
  Frontend/VIAProMa/Assets/Scripts/SaveLoadSystem/Core/SaveLoadManager.cs
  Frontend/VIAProMa/Assets/Scripts/UI/AdvancedSettings/AdvancedSettingsMenu.cs
Labels: bug, Team PMSL, mixed-reality-lab

#557 Added local analytics data export
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/Advanced Settings.prefab
  Frontend/VIAProMa/Assets/Scripts/Analytics/FileExport.meta
  Frontend/VIAProMa/Assets/Scripts/Analytics/FileExport/ExportAnalytics.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/FileExport/ExportAnalytics.cs.meta
  Frontend/VIAProMa/ProjectSettings/BurstAotSettings_WSAPlayer.json
  Frontend/VIAProMa/ProjectSettings/CommonBurstAotSettings.json
Labels: enhancement, Team PMSL, mixed-reality-lab

#558 Fixed telemetry path and deleted redundant Advanced Settings Menu from scene.
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsManager.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/FileExport/ExportAnalytics.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observer.cs
Labels: enhancement, Team PMSL, mixed-reality-lab

#560 Further undo redo commands are now possible
  Frontend/VIAProMa/Assets/Scripts/Shelf/IssueShelf/IssuesLoader.cs
  Frontend/VIAProMa/Assets/Scripts/Shelf/ProjectLoadShelf/ProjectLoader.cs
  Frontend/VIAProMa/Assets/Scripts/Shelf/VisualizationShelf/VisualizationInstantiator.cs
  Frontend/VIAProMa/Assets/Scripts/Shelf/VisualizationShelf/VisualizationShelf.cs
  Frontend/VIAProMa/Assets/Scripts/UI/AppBar/AppBarActions.cs
  Frontend/VIAProMa/Assets/Scripts/UI/Main Menu Cube/MainMenu.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/CommandProcessor.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/Delete Object Command.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/Delete Object Command.cs.meta
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/InitiateObjectCommand.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/InitiateObjectCommand.cs.meta
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/MoveObejctCommand.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/MoveObejctCommand.cs.meta
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/ProgressBarHandleCommand.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/ScaleKanbanBoardCommand.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/UndoRedoManager.cs
  Frontend/VIAProMa/Assets/Scripts/Visualizations/Progress Bar/ProgressBarHandle.cs
Labels: enhancement

#561 Updated some analytics backend urls
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsManager.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observer.cs
Labels: enhancement, Team PMSL, mixed-reality-lab

#563 Added Export function with different file formats.
  Frontend/VIAProMa/Assets/Prefabs/UI/DropdownMenu/DropdownMenu.prefab
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/Advanced Settings.prefab
  Frontend/VIAProMa/Assets/Scenes/MainScene.unity
  Frontend/VIAProMa/Assets/Scripts/Analytics/FileExport/DropdownCapability.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/FileExport/DropdownCapability.cs.meta
  Frontend/VIAProMa/Assets/Scripts/Analytics/FileExport/ExportAnalytics.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/FileExport/IDropdownConfiguration.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/FileExport/IDropdownConfiguration.cs.meta
  Frontend/VIAProMa/Assets/Scripts/UI/AdvancedSettings/AdvancedSettingsMenu.cs
  Frontend/VIAProMa/Assets/Scripts/UI/AdvancedSettings/ExportSelection.cs
  Frontend/VIAProMa/Assets/Scripts/UI/AdvancedSettings/ExportSelection.cs.meta
  Frontend/VIAProMa/Assets/Scripts/UI/AdvancedSettings/ExportSelectionDropdownMenu.cs
  Frontend/VIAProMa/Assets/Scripts/UI/AdvancedSettings/ExportSelectionDropdownMenu.cs.meta
Labels: enhancement, Team PMSL, mixed-reality-lab

#567 Fully implemented browser with sketchfab funtionality and sync + save
  Frontend/VIAProMa/Assets/Prefabs/3DImport/Resources/NetworkModel.prefab
  Frontend/VIAProMa/Assets/Prefabs/Resources/ImportedModel.prefab
  Frontend/VIAProMa/Assets/Prefabs/Resources/ImportedModel.prefab.meta
  Frontend/VIAProMa/Assets/Scenes/MainScene.unity
  Frontend/VIAProMa/Assets/Scripts/3DImport/ImportManager.cs
  Frontend/VIAProMa/Assets/Scripts/3DImport/NetworkImportModel.cs
  Frontend/VIAProMa/UserSettings/Layouts/default-2021.dwlt
Labels: mixed-reality-lab

#566 Redesigned Observer Pattern
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsObservibleComponent.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsObservibleComponent.cs.meta
  Frontend/VIAProMa/Assets/Scripts/Analytics/GazableComponents/GazableIssueCard.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observer.cs
  Frontend/VIAProMa/Assets/Scripts/Shelf/Widgets/CopyMover.cs
Labels: Team PMSL, mixed-reality-lab

#570 Changed the User Interface for Analytics Settings and renamed GameObjects accordingly
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/Advanced Settings.prefab
  Frontend/VIAProMa/Assets/Scenes/MainScene.unity
Labels: enhancement, Team PMSL, mixed-reality-lab

#530 Adding Analytics Backend
  Backend/.gitignore
  Backend/immersive_project_management_service/build.gradle
  Backend/immersive_project_management_service/src/main/java/i5/las2peer/services/immersiveProjectManagementService/AnalyticsResource.java
  Backend/immersive_project_management_service/src/main/java/i5/las2peer/services/immersiveProjectManagementService/ImmersiveProjectManagementService.java
  Backend/immersive_project_management_service/src/main/java/i5/las2peer/services/immersiveProjectManagementService/ProjectSettingsResource.java
  Backend/immersive_project_management_service/src/main/java/i5/las2peer/services/immersiveProjectManagementService/i5/las2peer/services/immersiveProjectManagementService/dataModel/LogPoint/LogPointLRS.java
Labels: enhancement, Team PMSL, mixed-reality-lab

#568 Alternative (LRS) implementation
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsManager.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsObservibleComponent.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/GazableComponents/GazableIssueCard.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/LogTypes/LogpointLRSExportable.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/LogTypes/LogpointLRSExportable.cs.meta
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observers.meta
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observers/DummyObserver.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observers/DummyObserver.cs.meta
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observers/LRSBackendObserver.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observers/LRSBackendObserver.cs.meta
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observers/LRSObserver.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observers/LRSObserver.cs.meta
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observers/Observer.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observers/Observer.cs.meta
  Frontend/VIAProMa/Assets/Scripts/Shelf/Widgets/CopyMover.cs
  Frontend/VIAProMa/Assets/Scripts/SiteLogin/LearningLayersLogin.cs
Labels: Team PMSL, mixed-reality-lab

#573 Changed Undo Button design, added Command to Avatar Controller
  Frontend/VIAProMa/Assets/Prefabs/UI/Menus/UndoRedoMenu.prefab
  Frontend/VIAProMa/Assets/Scripts/Multiplayer/Avatars/Customization System/Configurator/AvatarConfigurator.cs
  Frontend/VIAProMa/Assets/Scripts/UI/AppBar/AppBarActions.cs
  Frontend/VIAProMa/Assets/Scripts/UI/Main Menu Cube/MainMenu.cs
  Frontend/VIAProMa/Assets/Scripts/UI/UndoRedoSystem/UIHistory.cs
  Frontend/VIAProMa/Assets/Scripts/UndoRedoSystem/InitiateObjectCommand.cs
Labels: enhancement

#575 Implemented settings and project id syncing for multiple clients across saves.
  Frontend/VIAProMa/Assets/Scenes/MainScene.unity
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsManager.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsObservibleComponent.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/AnalyticsSettings.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/FileExport/ExportAnalytics.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/GazableComponents/GazableIssueCard.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observers/DummyObserver.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observers/LRSBackendObserver.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observers/LRSObserver.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/wiki.md
  Frontend/VIAProMa/Assets/Scripts/Multiplayer/MultiplayerManager.cs
  Frontend/VIAProMa/Assets/Scripts/ProjectSettings.meta
  Frontend/VIAProMa/Assets/Scripts/ProjectSettings/ProjectSettings.cs
  Frontend/VIAProMa/Assets/Scripts/ProjectSettings/ProjectSettings.cs.meta
  Frontend/VIAProMa/Assets/Scripts/ProjectSettings/SettingsManager.cs
  Frontend/VIAProMa/Assets/Scripts/ProjectSettings/SettingsManager.cs.meta
  Frontend/VIAProMa/Assets/Scripts/SaveLoadSystem/Core/SaveLoadManager.cs
  Frontend/VIAProMa/Assets/Scripts/Shelf/Widgets/CopyMover.cs
  Frontend/VIAProMa/Assets/Scripts/UI/AdvancedSettings/AdvancedSettingsMenu.cs
Labels: enhancement, Team PMSL, mixed-reality-lab

#574 Use LRS for all implemented Observables
  Frontend/VIAProMa/Assets/Scripts/Analytics/GazableComponents/GazableIssueCard.cs
  Frontend/VIAProMa/Assets/Scripts/Shelf/Widgets/CopyMover.cs
Labels: enhancement, Team PMSL, mixed-reality-lab

#572 Added comments to Observers
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observers/DummyObserver.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observers/LRSBackendObserver.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observers/LRSObserver.cs
  Frontend/VIAProMa/Assets/Scripts/Analytics/Observers/Observer.cs
Labels: documentation, Team PMSL, mixed-reality-lab
